baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Anubis2"
theme = "anubis2"
paginate = 5

disqusShortname = ""


[author]
name = "Junyi"

[params]
author = "Junyi"
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true

colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
mathjax = true
toc = true

# Graphcomment support
graphcommentId = ""

GiscusRepo = "Junyi-99/hugo-theme-anubis2"
GiscusRepoId = "R_kgDOLEp76Q"
GiscusCategory = "General"
GiscusCategoryId = "DIC_kwDOLEp76c4CcbPS"
GiscusLazyLoad = false
GiscusDataMapping = "pathname"

customCSS = ["css/custom1.scss", "css/custom2.css"]

[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/Junyi-99/hugo-theme-anubis2"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/"

[[params.social]]
id = "email"
url = "example@example.com"

[[params.social]]
id = "facebook"
url = "#"

[[params.social]]
id = "instagram"
url = "#"

[[params.social]]
id = "netease-music"
url = "#"

[[params.social]]
id = "telegram"
url = "#"

[[params.social]]
id = "x"
url = "#"

[[params.social]]
id = "youtube"
url = "#"

[languages.en]
languageName = "English"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages.pl]
languageName = "Polski"


[[languages.pl.menu.main]]
identifier = "home"
name = "Strona Główna"
url = "/"
weight = 1

[[languages.pl.menu.main]]
identifier = "about"
name = "O Hugo"
url = "/about/"
weight = 2

[[languages.pl.menu.main]]
identifier = "tags"
name = "Tagi"
url = "/tags/"
weight = 3

[[languages.pl.menu.main]]
identifier = "archive"
name = "Archiwum"
url = "/posts/"
weight = 4

[languages.pl.params]
languageCode = "pl-pl"

[languages.zh]
languageName = "Chinese"

[[languages.zh.menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[languages.zh.menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 2

[[languages.zh.menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3

[[languages.zh.menu.main]]
identifier = "archive"
name = "归档"
url = "/posts/"
weight = 4

[languages.zh.params]
languageCode = "zh-cn"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup.goldmark.renderer]
unsafe = true


[params.UmamiAnalytics]
enabled = true
dnt = false
id = "e4f661ff-9a8c-49d4-b3cc-2efe553e3973"                                            # Website ID
datacache = false
url = "https://eu.umami.is/script.js"
shareUrl = "https://eu.umami.is/share/RIETUMwZn4IBMIr8/hugo-theme-anubis2.netlify.app"
