baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Anubis2 Demo Site"
theme = "anubis2"
disqusShortname = ""

[pagination]
pagerSize = 5


[params.author]
name = "Junyi"
email  = "me@junyi.dev"
location = "Singapore"

[params]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true

# icp = "京ICP备xxxxx号-1" # for China ICP license
# police = "京公网安备 12345678号" # for China police beian

colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

# Graphcomment support
graphcommentId = ""

GiscusRepo = "Junyi-99/hugo-theme-anubis2"
GiscusRepoId = "R_kgDOLEp76Q"
GiscusCategory = "General"
GiscusCategoryId = "DIC_kwDOLEp76c4CcbPS"
GiscusLazyLoad = false
GiscusDataMapping = "pathname"

customCSS = ["custom-css/custom1.scss", "custom-css/custom2.css"]

social = [
    { id = "docs", url = "https://gohugo.io/documentation/" },
    { id = "github", url = "https://github.com/Junyi-99/hugo-theme-anubis2" },
    { id = "linkedin", url = "https://www.linkedin.com/" },
    { id = "email", url = "example@example.com" },
    { id = "facebook", url = "#" },
    { id = "instagram", url = "#" },
    { id = "netease-music", url = "#" },
    { id = "telegram", url = "#" },
    { id = "x", url = "#" },
    { id = "youtube", url = "#" },
    { id = "bluesky", url = "#" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "English"

[languages.pl]
languageName = "Polski"

[[languages.pl.menu.main]]
identifier = "home"
name = "Strona Główna"
url = "/"
weight = 1

[[languages.pl.menu.main]]
identifier = "about"
name = "O Hugo"
url = "/about/"
weight = 2

[[languages.pl.menu.main]]
identifier = "tags"
name = "Tagi"
url = "/tags/"
weight = 3

[[languages.pl.menu.main]]
identifier = "archive"
name = "Archiwum"
url = "/posts/"
weight = 4

[languages.pl.params]
languageCode = "pl-pl"

[languages.zh]
languageName = "Chinese"

[[languages.zh.menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[languages.zh.menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 2

[[languages.zh.menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3

[[languages.zh.menu.main]]
identifier = "archive"
name = "归档"
url = "/posts/"
weight = 4

[languages.zh.params]
languageCode = "zh-cn"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "d01ce82c-c8f4-4714-ba37-ba4899f2a885"                                            # Website ID
datacache = false
url = "https://umami.xtra.science/script.js"
shareUrl = "https://umami.xtra.science/share/Fy0goUn0b9rrxxGe/hugo-theme-anubis2.netlify.app"

[params.GoogleAnalytics]
enabled = true
gtag = "G-32F16X8HLF"